[params.giscus]
    data_repo="wanda-os/chat"
    data-repo-id="R_kgDOL19Baw"    
    data_category="Announcements"
    data_category_id="DIC_kwDOL19Ba84CfFG-"
    data_mapping="pathname"
    data_reactions_enabled="1"
    data_emit_metadata="0"
    data_theme="light"
    data_lang="en"
    crossorigin="anonymous"
